data_source datademo:
     type: snowflake
     username: Akshaydode
     password: Akshay@111
     account: za90521.central-india.azure
     database: SNOWFLAKE_DEMO 
     warehouse: COMPUTE_WH
     role: ACCOUNTADMIN
     session_parameters:
       QUERY_TAG: soda-queries
       QUOTED_IDENTIFIERS_IGNORE_CASE: false
     schema: CUST_DETAILS

soda_cloud:
  host: cloud.us.soda.io
  api_key_id: 8b6a5a68-1030-41c9-aa30-5b0a0626945a
  api_key_secret: iyDEXSaZZixU024myPuC8hpHky8Ds953twnvpI-gHvQxg6zPBFdMhg
