data_source datademo:
     type: snowflake
     username: ANKITPALIWAL
     password: @Nki1234
     account: ok95781.central-india.azure
     database: SNOWFLAKE_DEMO 
     warehouse: COMPUTE_WH
     role: ACCOUNTADMIN
     session_parameters:
       QUERY_TAG: soda-queries
       QUOTED_IDENTIFIERS_IGNORE_CASE: false
     schema: CUST_DETAILS

soda_cloud:
  host: cloud.us.soda.io
  api_key_id: 25fbe214-29bb-4e9a-9041-3a5bc5251836
  api_key_secret: 3lo_uwA4-aXFts7n8rsbF5mhPh2XUWT7ArxxZeIZbFdv6EmBm38-dg
